/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Allay Design (https://sketchfab.com/Alister.Dsouza)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/interior-scene-45ddbbc4c2dc4f8ca9ed99da9a78326a
Title: Interior Scene
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const HeroHome = (props) => {
  const { nodes, materials } = useGLTF('/models/interior_scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.328]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completepolySurface138_Interior_scene_completeaiStandardSurface44_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface44}
          
        />
     
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completepolySurface138_Interior_scene_completeaiStandardSurface45_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface45}
        />
      </group>
      <group position={[0, 0, -0.328]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completepolySurface139_Interior_scene_completeaiStandardSurface44_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface44}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completepolySurface139_Interior_scene_completeaiStandardSurface46_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface46}
        />
      </group>
      <group position={[-0.184, -0.026, -0.045]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completehouse1_Interior_scene_completeaiStandardSurface42_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.Interior_scene_completehouse1_Interior_scene_completeaiStandardSurface43_0
              .geometry
          }
          material={materials.Interior_scene_completeaiStandardSurface43}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface151_Interior_scene_completeaiStandardSurface89_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface89}
        position={[2.257, -10.577, -6.449]}
        rotation={[0, -0.888, 0]}
        scale={[2.902, 0.095, 2.841]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completeroof_Interior_scene_completeaiStandardSurface87_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface87}
        position={[0, 17.1, 0]}
        scale={[56.112, 66.552, 63.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface141_Interior_scene_completeaiStandardSurface49_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface49}
        position={[0, 0, -0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface142_Interior_scene_completeaiStandardSurface48_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface48}
        position={[0, 0, -0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface143_Interior_scene_completeaiStandardSurface47_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface47}
        position={[0, 0, -0.328]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completematress_Interior_scene_completeaiStandardSurface85_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface85}
        position={[0, -16.537, 0]}
        scale={[22.386, 0.904, 34.945]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepDisc4_Interior_scene_completeaiStandardSurface75_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface75}
        position={[-14.094, -3.049, -20.465]}
        rotation={[0.248, 0.04, 0.156]}
        scale={1.907}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepDisc1_Interior_scene_completeaiStandardSurface39_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface39}
        position={[0, -10.81, -8.755]}
        scale={5.901}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface11_Interior_scene_completeaiStandardSurface39_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface39}
        position={[0, 0, 0.087]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface22_Interior_scene_completeaiStandardSurface75_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface75}
        position={[-41, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepDisc3_Interior_scene_completeaiStandardSurface75_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface75}
        position={[-20.284, -9.89, -28.44]}
        scale={[2.974, 5.795, 2.974]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface5_Interior_scene_completeaiStandardSurface80_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface80}
        position={[0, 17.1, 0]}
        scale={[56.112, 66.552, 63.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder11_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[34.778, 7.459, -19.126]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.089}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder12_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[34.778, 5.448, -19.122]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.089}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface8_Interior_scene_completeaiStandardSurface80_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface80}
        position={[0, 17.1, 0]}
        scale={[56.112, 66.552, 63.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepCube10_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface31_Interior_scene_completeaiStandardSurface82_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface82}
        position={[0, 17.1, 0]}
        scale={[56.112, 66.552, 63.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepSphere1_Interior_scene_completeaiStandardSurface33_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface33}
        position={[-20.284, -7.437, -28.44]}
        scale={1.801}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCube21_Interior_scene_completeaiStandardSurface58_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface58}
        position={[-20.309, -9.219, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder20_Interior_scene_completeaiStandardSurface83_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface83}
        position={[24.739, -14.056, -22.361]}
        scale={1.289}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder21_Interior_scene_completeaiStandardSurface83_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface83}
        position={[26.48, -14.45, -17.849]}
        scale={[1.208, 1.065, 1.208]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder22_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[-0.181, 14.292, 0]}
        scale={[0.047, 4.591, 0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface40_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[2.203, 9.537, 0]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.047, 4.591, 0.047]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface41_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[0.749, 9.542, -0.011]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface42_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[0.749, 9.542, -0.011]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface43_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[5.029, 9.542, -0.011]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface44_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[5.177, 9.842, -1.124]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface45_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[6.053, 9.593, -1.898]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface46_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[8.925, 9.542, -1.716]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface47_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
        position={[8.925, 9.53, -2.667]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.031, 3.075, 0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder19_Interior_scene_completeaiStandardSurface36_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface36}
        position={[-1.56, -9.42, -9.319]}
        scale={[0.472, 0.525, 0.472]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder38_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup29_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder44_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder45_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup39_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder46_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup40_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup41_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder47_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder48_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup42_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder49_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup43_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[0.277, -5.192, 1.22]}
        rotation={[0.191, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface57_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[4.737, 14.679, 0.979]}
        rotation={[-0.131, -0.443, -1.956]}
        scale={0.077}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface61_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[4.306, 16.14, -3.546]}
        rotation={[-0.17, -0.383, -1.047]}
        scale={0.077}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface65_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.307, 1.659, 2.617]}
        rotation={[-0.283, 0.068, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface69_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[0.336, 0.002, 0.004]}
        rotation={[-0.001, 0.069, 0.015]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface73_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-6.188, 2.253, 6.542]}
        rotation={[-0.648, -0.185, -0.226]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface77_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[6.039, 12.01, 5.449]}
        rotation={[-2.141, 0.278, 1.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface86_Interior_scene_completeaiStandardSurface21_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface88_Interior_scene_completeaiStandardSurface21_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface48_Interior_scene_completeaiStandardSurface60_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface60}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface98_Interior_scene_completeaiStandardSurface79_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface79}
        position={[32.736, -5.556, -9.929]}
        scale={[1.638, 0.997, 1.638]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder296_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup55_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder297_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder298_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup56_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder299_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup57_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup58_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder300_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup59_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface99_Interior_scene_completeaiStandardSurface21_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-1.892, 3.179, -3.801]}
        rotation={[-Math.PI, -1.114, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface100_Interior_scene_completeaiStandardSurface21_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-1.892, 3.179, -3.801]}
        rotation={[-Math.PI, -1.114, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface101_Interior_scene_completeaiStandardSurface63_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface63}
        position={[-1.892, 3.179, -3.801]}
        rotation={[-Math.PI, -1.114, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder301_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completegroup60_Interior_scene_completeaiStandardSurface21_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface21}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder302_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-3.109, -2.013, -4.09]}
        rotation={[2.728, -1.079, 2.773]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder307_Interior_scene_completeaiStandardSurface36_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface36}
        position={[-2.833, -9.487, -9.319]}
        scale={[0.472, 0.496, 0.472]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder308_Interior_scene_completeaiStandardSurface52_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface52}
        position={[18.945, 0.073, 25.885]}
        rotation={[0.013, 0, 0]}
        scale={2.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepPlane27_Interior_scene_completeaiStandardSurface53_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface53}
        position={[18.945, 0.073, 25.885]}
        rotation={[0.013, 0, 0]}
        scale={2.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface104_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[18.945, 0.073, 25.885]}
        rotation={[0.013, 0, 0]}
        scale={2.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder310_Interior_scene_completeaiStandardSurface55_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface55}
        position={[18.945, 0.073, 25.885]}
        rotation={[0.013, 0, 0]}
        scale={2.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepSphere14_Interior_scene_completeaiStandardSurface51_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface51}
        position={[18.945, 0.073, 25.885]}
        rotation={[0.013, 0, 0]}
        scale={2.306}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder293_Interior_scene_completeaiStandardSurface61_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface61}
        position={[-0.187, -0.149, 0.528]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface114_Interior_scene_completeaiStandardSurface80_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface80}
        position={[0.658, 17.1, 9.409]}
        scale={[56.112, 66.552, 63.925]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder303_Interior_scene_completeaiStandardSurface35_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface35}
        position={[-2.416, -12.796, -8.755]}
        scale={2.501}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder304_Interior_scene_completeaiStandardSurface37_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface37}
        position={[0.818, -10.212, -10.411]}
        scale={0.489}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder305_Interior_scene_completeaiStandardSurface38_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface38}
        position={[1.639, -10.247, -11.34]}
        scale={[0.278, 0.457, 0.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface102_Interior_scene_completeaiStandardSurface37_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface37}
        position={[2.572, -10.232, -10.426]}
        scale={[0.278, 0.457, 0.278]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface112_Interior_scene_completeaiStandardSurface81_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface81}
        position={[0, 0, -0.267]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepDisc2_Interior_scene_completeaiStandardSurface75_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface75}
        position={[20.634, -9.911, -27.687]}
        scale={[3.036, 5.916, 3.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface13_Interior_scene_completeaiStandardSurface75_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface75}
        position={[-0.521, 0.186, 1.347]}
        scale={1.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder16_Interior_scene_completeaiStandardSurface77_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface77}
        position={[21.327, -4.177, -27.687]}
        scale={[1.53, 1.4, 1.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder18_Interior_scene_completeaiStandardSurface78_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface78}
        position={[-0.618, 0.176, 1.347]}
        scale={1.021}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder17_Interior_scene_completeaiStandardSurface76_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface76}
        position={[0, -0.022, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface33_Interior_scene_completeaiStandardSurface50_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface50}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepPlane3_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder311_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[35.438, 7.459, 1.173]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.089}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepCube22_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
        position={[0.66, 0, 20.299]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepPlane29_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
        position={[0.66, 0, 20.299]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder312_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[35.438, 5.448, 1.177]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.089}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepSphere8_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder50_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Interior_scene_completepPlane17_Interior_scene_completelambert5_0.geometry}
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface58_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface59_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder53_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface56_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder52_Interior_scene_completelambert5_0.geometry
        }
        material={materials.Interior_scene_completelambert5}
        position={[-16.911, 4.102, 22.105]}
        scale={1.796}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface115_Interior_scene_completeaiStandardSurface13_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface13}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepSphere4_Interior_scene_completeaiStandardSurface29_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface29}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder27_Interior_scene_completeaiStandardSurface22_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completebulbpolySurface80_Interior_scene_completebulbaiStandardSurface34_0
            .geometry
        }
        material={materials.Interior_scene_completebulbaiStandardSurface34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completebulbpolySurface82_Interior_scene_completebulbaiStandardSurface37_0
            .geometry
        }
        material={materials.Interior_scene_completebulbaiStandardSurface37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completebulbpolySurface91_Interior_scene_completebulbaiStandardSurface25_0
            .geometry
        }
        material={materials.Interior_scene_completebulbaiStandardSurface25}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completebulbpCylinder1_Interior_scene_completebulbaiStandardSurface33_0
            .geometry
        }
        material={materials.Interior_scene_completebulbaiStandardSurface33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completebulbpolySurface86_Interior_scene_completebulbaiStandardSurface36_0
            .geometry
        }
        material={materials.Interior_scene_completebulbaiStandardSurface36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCylinder313_Interior_scene_completeaiStandardSurface36_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface36}
        position={[19.967, -8.53, -28.263]}
        scale={[0.472, 0.525, 0.472]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface150_Interior_scene_completeaiStandardSurface79_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface79}
        position={[25.757, -16.322, -29.448]}
        scale={[1.638, 0.997, 1.638]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface103_Interior_scene_completeaiStandardSurface54_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface144_Interior_scene_completeaiStandardSurface64_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface64}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface145_Interior_scene_completeaiStandardSurface62_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface62}
        position={[-0.187, 0, 0.528]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface146_Interior_scene_completeaiStandardSurface84_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface84}
        position={[1.28, 0.841, 0]}
        rotation={[0, 0, -0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface148_Interior_scene_completeaiStandardSurface84_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface84}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface149_Interior_scene_completeaiStandardSurface73_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepolySurface149_Interior_scene_completeaiStandardSurface73_0_1
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_1
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_2
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_3
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_4
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_5
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_6
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_7
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_8
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_9
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_10
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_11
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_12
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_13
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa2PM3D_sofa_Interior_scene_completeaiStandardSurface73_0_14
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes
            .Interior_scene_completePM3D_sofa3PM3D_sofa_Interior_scene_completeaiStandardSurface73_0
            .geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface73}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Interior_scene_completepCube23_Interior_scene_completeaiStandardSurface86_0.geometry
        }
        material={materials.Interior_scene_completeaiStandardSurface86}
        position={[0, -15.82, -18.752]}
        scale={[30.926, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tyrescurtain_tyresaiStandardSurface88SG1_0.geometry}
        material={materials.tyresaiStandardSurface88SG1}
      />
    </group>
  )
}

useGLTF.preload('/models/interior_scene.glb')


export default HeroHome;